### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by 10Dozen** [10Dozen/dzn_AniMeme_Face#1]
Templates:
- [x] Template for 1:1
- [ ] Template for 1.5:1

Meshes:
 - [ ] Face mesh 1.5:1

Avatars:
 - [ ] Kama the Bullet 
 - [ ] Samuel L Jackson from Criminal Readings
 - [ ] WH40K Commissarr
 - [ ] WH40K Imperial Guard
 - [ ] Alexander WOTTAKWOT Nevsky
 - [ ]

**Comment by Cambusta** [comment]
_**SIDOROVICH**_

**Comment by Cambusta** [comment]
On a side note, I suggest leaving local and momentary Russian memes for a separate pack.
